//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imageblur {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int NumberOfTasks {
            get {
                return ((int)(this["NumberOfTasks"]));
            }
            set {
                this["NumberOfTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int PoolNodeCount {
            get {
                return ((int)(this["PoolNodeCount"]));
            }
            set {
                this["PoolNodeCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImageBlurPool")]
        public string PoolId {
            get {
                return ((string)(this["PoolId"]));
            }
            set {
                this["PoolId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteJob {
            get {
                return ((bool)(this["DeleteJob"]));
            }
            set {
                this["DeleteJob"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteContainer {
            get {
                return ((bool)(this["DeleteContainer"]));
            }
            set {
                this["DeleteContainer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImageBlurJob")]
        public string JobId {
            get {
                return ((string)(this["JobId"]));
            }
            set {
                this["JobId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeletePool {
            get {
                return ((bool)(this["DeletePool"]));
            }
            set {
                this["DeletePool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"sourceimages/sourceimage1.jpg,sourceimages/sourceimage2.jpg,sourceimages/sourceimage3.jpg,sourceimages/sourceimage4.jpg,sourceimages/sourceimage5.jpg,sourceimages/sourceimage6.jpg,sourceimages/sourceimage7.jpg,sourceimages/sourceimage8.jpg,sourceimages/sourceimage9.jpg")]
        public string SourceImageNames {
            get {
                return ((string)(this["SourceImageNames"]));
            }
            set {
                this["SourceImageNames"] = value;
            }
        }
    }
}
